### ISSUE TITLE
ImportError: No module named finance

### ISSUE THREAD

**Issue by rmaranhao** [csantosbh/bovespatools#1]
Olá.
Em primeiro lugar parabéns pelo crawler da Bovespa.
Experimentando, conseguir atualizar dados de 2018 e 2017, bem como as ações corporativas.

Quanto tento browse_assets, obtenho o seguinte erro:
`root@ubuntu:/bovespa/bovespatools# ./browse_assets.py 
Traceback (most recent call last):
  File "./browse_assets.py", line 183, in <module>
    if not plot_with_lines(favourite_assets[current_asset]['code'], int(args.num_days)):
  File "./browse_assets.py", line 83, in plot_with_lines
    from matplotlib.finance import candlestick_ochl
ImportError: No module named finance
`
Estou usando uma VM Ubuntu 18.04 para testar seu código.

**Comment by rmaranhao** [comment]
Ei!

a biblioteca finance foi separada do matplotlib.

Assim, a linha 83 teve que ser alterada para:
`    from mpl_finance import candlestick_ochl
`

So far, so good.

**Comment by csantosbh** [comment]
Olá Roberto! Muito obrigado pelo report! Se você quiser, pode fazer o pull request com a mudança mencionada que eu a incorporarei no repositório.

**Comment by rmaranhao** [comment]
Ei Cláudio,
bom dia.

Na verdade eu queria saber se te interessa desenvolver o crawler em um
identificador de padrões.

Quero um sistema que me alerte caso uma ação caia mais que duas vezes seu
desvio padrão, por exemplo.

Eu vou fazer, mas como seu código é limpo e objetivo, achei que poderíamos
estabelecer uma parceria.

Um abraço,
Roberto.


Um grande abraço,
Roberto.

-- 
Roberto Maranhão - Maranhão Consultoria
r.maranhao@gmail.com
(5531) 8482 4456

2018-08-02 15:54 GMT-03:00 Claudio <notifications@github.com>:
